/* tslint:disable */
/**
 * This file was automatically generated by the bindingz plugin.
 */

export interface UrnJsonschemaComMonadiccloudBindingzContractPluginExampleGradleFooBarEvent {
  id?: string;
  name?: string;
  bars?: UrnJsonschemaComMonadiccloudBindingzContractPluginExampleGradleFooBarEventBar[];
  [k: string]: any;
}
export interface UrnJsonschemaComMonadiccloudBindingzContractPluginExampleGradleFooBarEventBar {
  barId?: string;
  [k: string]: any;
}
